/*
 * LineToolPanel.java
 *
 * Created on 2007/11/07, 14:19
 */

package jtools.jcontrol;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import jtools.JAbstractTool;
import jtools.JLineTool;
import jscreen.JEnvironment;

/**
 *
 * @author  i002060
 */
public class RotateToolPanel extends javax.swing.JPanel implements ChangeListener{
    //private  static final int WIDTH=269,HEIGHT=97;
    //
    private JDialog dialog;
    private JAbstractTool dragger=null;
    private boolean cancel=true;
    /**
     * Creates new form LineToolPanel
     */
    private static Window getRootWindow(Container c){
        if (c instanceof Window) return (Window)c;
        return getRootWindow(c.getParent());
    }
    public RotateToolPanel(Window frame){
        dialog=new JDialog(frame);
        dialog.setContentPane(this);
        initComponents();
        //this.setPreferredSize(new Dimension(WIDTH,HEIGHT));
        //Insets inset=dialog.getInsets();
        //dialog.setSize(new Dimension(WIDTH+inset.left+inset.right,HEIGHT+inset.top+inset.bottom));
        dialog.setLocationByPlatform(true);
        dialog.setResizable(false);
        dialog.getRootPane().setDefaultButton(okButton);
        dialog.setDefaultCloseOperation(dialog.DISPOSE_ON_CLOSE);
        dialog.setModal(true);
        dialog.setTitle("回転");
        //
        angle.addChangeListener(this);
        angleSlider.addChangeListener(this);
        angle.setValue(JEnvironment.DEFAULT_THETA);
        angleSlider.setValue(-JEnvironment.DEFAULT_THETA);
        
        
        dialog.pack();
        int centerX=frame.getX()+(frame.getWidth()-dialog.getWidth())/2;
        int centerY=frame.getY()+(frame.getHeight()-dialog.getHeight())/2;
        dialog.setLocation(centerX,centerY);
        dialog.setVisible(true);
        
    }
    public RotateToolPanel(JAbstractTool dragger) {
        this(getRootWindow(dragger.getViewer().getRootPane().getParent()));
        this.dragger=dragger;
        dialog.setTitle(dragger.presentationName() +"オプション");
        //
    }
    public boolean isCanceled(){
        return cancel;
    }
    public boolean isCopy(){
        return copy.isSelected();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        copy = new javax.swing.JCheckBox();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        angleSlider = new jtools.jcontrol.AngleSlider();
        angle = new jtools.jcontrol.JDAngleTextField();

        copy.setText("コピー");
        copy.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        copy.setMargin(new java.awt.Insets(0, 0, 0, 0));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("キャンセル");
        cancelButton.setDefaultCapable(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("回転角");

        javax.swing.GroupLayout angleSliderLayout = new javax.swing.GroupLayout(angleSlider);
        angleSlider.setLayout(angleSliderLayout);
        angleSliderLayout.setHorizontalGroup(
            angleSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        angleSliderLayout.setVerticalGroup(
            angleSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(angleSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(angle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(copy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(angleSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(angle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(copy)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
// TODO add your handling code here:
        cancel=true;
        dialog.setVisible(false);
        dialog.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
// TODO add your handling code here:
        cancel=false;
        JEnvironment.DEFAULT_THETA=((Number)angle.getValue()).doubleValue();
        dialog.setVisible(false);
        dialog.dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    
    public void stateChanged(ChangeEvent e) {
        if (e.getSource()==angleSlider){
            angle.setValue(new Double(-angleSlider.getValue()));
        }else if (e.getSource()==angle){
            angleSlider.setValue(-((Double)angle.getValue()).floatValue());
        }
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jtools.jcontrol.JDAngleTextField angle;
    private jtools.jcontrol.AngleSlider angleSlider;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox copy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
}
