/*
 * lisence.java
 *
 * Created on 2008/06/29, 9:49
 */
package jdraw;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.io.IOException;
import java.net.URL;
import javax.swing.JEditorPane;

/**
 *
 * @author  takashi
 */
public class Licence extends javax.swing.JDialog {

    /** Creates new form lisence */
    public Licence(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public static void showAsDialog(JDrawApplication parent) {
        //default size 400×180
        Licence licence = new Licence(parent, true);
        licence.setTitle("ライセンス");
        Dimension psize = new Dimension(400, 180);
        int x = (parent.getWidth() - psize.width) / 2;
        int y = (parent.getHeight() - psize.height) / 2;
        licence.setSize(psize);
        licence.setLocation(x, y);
        licence.setVisible(true);
    }
    private class MyEditorPane extends JEditorPane{
        public MyEditorPane(URL url) throws IOException{
            super(url);
        }
        @Override
        public void paint(Graphics g){
            Graphics2D g2=(Graphics2D)g;
            g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_LCD_HBGR);
            super.paint(g);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JEditorPane();
        try{
            jTextPane1 = new MyEditorPane(getClass().getResource("/licence.htm"));
        }catch(Exception e){
            e.printStackTrace();
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Licence dialog = new Licence(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
