/*
 * BluerPanel.java
 *
 * Created on 2007/12/21, 18:13
 */

package jui.color;

import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JComponent;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import jobject.effector.JDropShadowEffector;
import jui.color.JDColorPanel;

/**
 *
 * @author  takashi
 */
public class DropShadowPanel extends javax.swing.JDialog{
    static Dimension size=new Dimension(251,125);
    private boolean desided=false;
    private JDColorPanel panel=null;
    private static double ofsX=4;
    private static double ofsY=4;
    private static int radius=4;
    private static Color dColor=new Color(0f,0f,0f,0.8f);
    /** Creates new form BluerPanel */
    private static Frame getRootWindow(Container c){
        if (c instanceof Frame) return (Frame)c;
        return getRootWindow(c.getParent());
    }
    public DropShadowPanel(JComponent cmp, boolean modal) {
        super(getRootWindow(cmp.getRootPane().getParent()), modal);
        initComponents();
        //this.setSize(size);
        this.setPreferredSize(size);
        radiusText.setModel(new SpinnerNumberModel(radius,-50,50,1));
        offsetX.setValue(new Double(ofsX));
        offsetY.setValue(new Double(ofsY));
        color.setColor(dColor);
        this.rootPane.setDefaultButton(ok);
        color.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent e){
                colorMousePressed(e);
            }
        });
        Point cp=new Point(0,0);
        SwingUtilities.convertPointToScreen(cp,cmp);
        this.setLocation(cp.x+(cmp.getWidth()-size.width)/2,cp.y+(cmp.getHeight()-size.height)/2);
        desided=false;
        this.setVisible(true);
    }
    public boolean isDesided(){
        return desided;
    }
    public JDropShadowEffector getEffector(){
        return new JDropShadowEffector(((Number)(radiusText.getValue())).floatValue(),((Number)offsetX.getValue()).floatValue()
        ,((Number)offsetY.getValue()).floatValue(),color.getColor());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPaintPreview1 = new jui.color.JDPaintPreview();
        jDPaintPreview2 = new jui.color.JDPaintPreview();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radiusText = new javax.swing.JSpinner();
        offsetX = new jtools.jcontrol.JDLengthTextField();
        offsetY = new jtools.jcontrol.JDLengthTextField();
        color = new jui.color.JDPaintPreview();

        javax.swing.GroupLayout jDPaintPreview1Layout = new javax.swing.GroupLayout(jDPaintPreview1);
        jDPaintPreview1.setLayout(jDPaintPreview1Layout);
        jDPaintPreview1Layout.setHorizontalGroup(
            jDPaintPreview1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDPaintPreview1Layout.setVerticalGroup(
            jDPaintPreview1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDPaintPreview2Layout = new javax.swing.GroupLayout(jDPaintPreview2);
        jDPaintPreview2.setLayout(jDPaintPreview2Layout);
        jDPaintPreview2Layout.setHorizontalGroup(
            jDPaintPreview2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDPaintPreview2Layout.setVerticalGroup(
            jDPaintPreview2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ぼかし");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setText("ぼかし:");

        jLabel2.setText("point");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.setDefaultCapable(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel5.setText("オフセットX:");

        jLabel6.setText("オフセットY:");

        jLabel7.setText("カラー:");

        javax.swing.GroupLayout colorLayout = new javax.swing.GroupLayout(color);
        color.setLayout(colorLayout);
        colorLayout.setHorizontalGroup(
            colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        colorLayout.setVerticalGroup(
            colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiusText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(offsetX, 0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(offsetY, 0, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(radiusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(offsetX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(offsetY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorMousePressed
// TODO add your handling code here:
        if (panel==null){
            panel=new JDColorPanel(color);
            panel.getDialog().setModal(true);
        }
        
        panel.setCurrentColor(color.getColor());
        panel.setPrevColor(color.getColor());
        panel.setAllowNull(false);
        panel.addChangeListener(new ChangeListener(){
            public void stateChanged(ChangeEvent e) {
                colorChanged(e);
            }
        });
        panel.showAsPopup(color);
    }//GEN-LAST:event_colorMousePressed
    private void colorChanged(ChangeEvent e){
        color.setColor(panel.getDisidedColor());
        this.repaint();
    }
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
// TODO add your handling code here:
        desided=false;
        this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
// TODO add your handling code here:
       desided=true;
       ofsX=((Number)(offsetX.getValue())).doubleValue();
       ofsY=((Number)offsetY.getValue()).doubleValue();
       radius=((Number)radiusText.getValue()).intValue();
       dColor=color.getColor();
       this.setVisible(false);
    }//GEN-LAST:event_okActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private jui.color.JDPaintPreview color;
    private jui.color.JDPaintPreview jDPaintPreview1;
    private jui.color.JDPaintPreview jDPaintPreview2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private jtools.jcontrol.JDLengthTextField offsetX;
    private jtools.jcontrol.JDLengthTextField offsetY;
    private javax.swing.JButton ok;
    private javax.swing.JSpinner radiusText;
    // End of variables declaration//GEN-END:variables
    
}
