/*
 * JLayerOption.java
 *
 * Created on 2008/05/17, 14:30
 */

package jui.layer;

import java.util.SortedMap;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import jedit.layeredit.ImageObjectOptionEdit;
import jobject.JImageObject;
import jobject.JPage;

/**
 *
 * @author  takashi
 */
public class JImageObjectOption extends javax.swing.JDialog implements ChangeListener {
    private JImageObject leaf;
    private JPage parent;
    /** Creates new form JLayerOption */
    public JImageObjectOption(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        alpha.setMinValue(new Float(0));
        alpha.setMaxValue(new Float(1f));
        alpha.setFloatValue(1f);
        alphaSlider.setMaxValue(255);
        alphaSlider.setMinValue(0);
        alpha.addChangeListener(this);
        alphaSlider.addChangeListener(this);
        
        
    }
    public void showDialog(JImageObject lf,JPage parent){
        this.parent=parent;
        this.leaf=lf;
        this.setTitle("イメージオプション");
        text.setText(leaf.getName());
        locked.setSelected(leaf.isLocked());
        visible.setSelected(leaf.isVisible());
        alpha.setFloatValue(lf.getAlpha());
        alphaSlider.setValue((int)(lf.getAlpha()*255));
        this.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        locked = new javax.swing.JCheckBox();
        visible = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        alphaSlider = new jui.color.JDSlider();
        alpha = new jtools.jcontrol.JDNumericTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setText("名称:");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.setDefaultCapable(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        locked.setText("ロック");
        locked.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        locked.setMargin(new java.awt.Insets(0, 0, 0, 0));

        visible.setText("可視");
        visible.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        visible.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel2.setText("アルファ:");

        alpha.setFormat("%.2f");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visible)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(locked)
                            .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(alphaSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alpha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ok)
                    .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancel)
                        .addComponent(alpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alphaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locked)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visible)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
// TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
// TODO add your handling code here:
        if (text.getText().equals(leaf.getName()) && locked.isSelected()==leaf.isLocked() && alpha.getFloatValue()==leaf.getAlpha()){
            this.setVisible(false);
            return;
        }
        if (!text.getText().equals(leaf.getName())){
            SortedMap map=leaf.getPage().getNameTable();
            if (map.containsKey(text.getText())){
                JOptionPane.showMessageDialog(this,"入力されたオブジェクトの名称は、他で使用されています.");
                text.setText(leaf.getName());
                text.requestFocus();
                return;
            }
        }
 
        //ObjectOptionEdit anEdit=new ObjectOptionEdit(leaf.getDocument().getViewer(),leaf,visible.isSelected(),locked.isSelected(),text.getText());
        Number al=(Number)alpha.getValue();
        ImageObjectOptionEdit anEdit=new ImageObjectOptionEdit(leaf.getDocument().getViewer(),leaf,visible.isSelected(),
                locked.isSelected(),al.floatValue(),text.getText());
        leaf.getDocument().fireUndoEvent(anEdit);
        leaf.getDocument().getViewer().repaint();
        this.getParent().repaint();
        this.setVisible(false);
        
    }//GEN-LAST:event_okActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jtools.jcontrol.JDNumericTextField alpha;
    private jui.color.JDSlider alphaSlider;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox locked;
    private javax.swing.JButton ok;
    private javax.swing.JTextField text;
    private javax.swing.JCheckBox visible;
    // End of variables declaration//GEN-END:variables

    @Override
    public void stateChanged(ChangeEvent e) {
        Object source=e.getSource();
        if (source==alpha){
            alphaSlider.setValue((int)alpha.getFloatValue());
        }else{
            alpha.setFloatValue(alphaSlider.getValue()/255f);
        }
        repaint();
    }
    
}
