/*
 * JLayerOption.java
 *
 * Created on 2008/05/17, 14:30
 */

package jui.layer;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.SortedMap;
import java.util.Vector;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import jedit.layeredit.LayerOptionEdit;
import jobject.JLayer;
import jobject.JPage;
import jscreen.JEnvironment;

/**
 *
 * @author  takashi
 */
public class JLayerOption extends javax.swing.JDialog {
    private boolean newLayer;
    private JLayer layer;
    private JPage parent;
    /** Creates new form JLayerOption */
    public JLayerOption(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        color.addMouseListener( new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                colorClicked(e);
            }
        });
        this.addWindowListener(new WindowAdapter(){
           public void windowClosing(WindowEvent e){
                layer=null;
                dispose();
           } 
        });
        
    }
    private void colorClicked(MouseEvent e){
        if (e.getClickCount()==1) return;
        Color nc=JColorChooser.showDialog(this,"レイヤーの色",color.getBackground());
        if (nc !=null){
            color.setBackground(nc);
        }
    }
    public JLayer getLayer(){
        return layer;
    }
    public void showDialog(JLayer layer,JPage parent){
        this.parent=parent;
        this.layer=layer;
        this.setTitle("レイヤーオプション");
        newLayer=false;
        if (layer==null){
            this.setTitle("新規レイヤー");
            newLayer=true;
            this.layer=new JLayer();
            this.layer.setName(parent.getProperName(this.layer.getPrefixer()));
            Vector<Color> colors =new Vector<Color>();
            for (int i=0;i<JEnvironment.PREVIEW_COLORS.length;i++){
                colors.add(JEnvironment.PREVIEW_COLORS[i]);
            }
            for (int i=0;i<parent.size();i++){
                colors.remove(parent.get(i).getPreviewColor());
            }
            if (colors.isEmpty())
                this.layer.setPreviewColor(JEnvironment.PREVIEW_COLORS[0]);
            else
                this.layer.setPreviewColor(colors.get(0));
        }
        text.setText(this.layer.getName());
        color.setBackground(this.layer.getPreviewColor());
        locked.setSelected(this.layer.isLocked());
        visible.setSelected(this.layer.isVisible());
        this.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        text = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        locked = new javax.swing.JCheckBox();
        visible = new javax.swing.JCheckBox();
        color = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        jLabel1.setText("\u540d\u79f0:");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jLabel2.setText("\u8272:");

        cancel.setText("Cancel");
        cancel.setDefaultCapable(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        locked.setText("\u30ed\u30c3\u30af");
        locked.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        locked.setMargin(new java.awt.Insets(0, 0, 0, 0));

        visible.setText("\u53ef\u8996");
        visible.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        visible.setMargin(new java.awt.Insets(0, 0, 0, 0));

        color.setBackground(new java.awt.Color(255, 51, 153));
        color.setAlignmentX(1.0F);
        color.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        color.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visible)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locked)
                            .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locked)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visible)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
// TODO add your handling code here:
        layer=null;
        dispose();
    }//GEN-LAST:event_cancelActionPerformed
    
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
// TODO add your handling code here:
        if (text.getText().equals(layer.getName()) && locked.isSelected()==layer.isLocked() &&
                visible.isSelected()==layer.isVisible() && color.getBackground().equals(layer.getPreviewColor())){
            this.setVisible(false);
            return;
        }
        if (!text.getText().equals(layer.getName())){
            SortedMap map=parent.getPage().getNameTable();
            //SortedMap map=layer.getPage().getNameTable();
            if (map.containsKey(text.getText())){
                JOptionPane.showMessageDialog(this,"入力されたレイヤーの名称は、他で使用されています.");
                text.setText(layer.getName());
                text.requestFocus();
                return;
            }
        }
        if (newLayer){
           layer.setPreviewColor(color.getBackground());
           layer.setName(text.getText());
           layer.setLocked(locked.isSelected());
           layer.setVisible(visible.isSelected());
        }else{
            LayerOptionEdit anEdit=new LayerOptionEdit(layer.getDocument().getViewer(),layer,visible.isSelected(),
                    locked.isSelected(),color.getBackground(),text.getText());
            layer.getDocument().fireUndoEvent(anEdit);
            layer.getDocument().getViewer().repaint();
            this.getParent().repaint();
            layer=null;
        }
        dispose();
    }//GEN-LAST:event_okActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel color;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox locked;
    private javax.swing.JButton ok;
    private javax.swing.JTextField text;
    private javax.swing.JCheckBox visible;
    // End of variables declaration//GEN-END:variables
    
}
