/*
 * JLayerOption.java
 *
 * Created on 2008/05/17, 14:30
 */

package jui.layer;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.SortedMap;
import java.util.Vector;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import jedit.layeredit.LayerOptionEdit;
import jedit.layeredit.ObjectOptionEdit;
import jobject.JLayer;
import jobject.JLeaf;
import jobject.JPage;
import jscreen.JEnvironment;

/**
 *
 * @author  takashi
 */
public class JObjectOption extends javax.swing.JDialog {
    private JLeaf leaf;
    private JPage parent;
    /** Creates new form JLayerOption */
    public JObjectOption(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    public void showDialog(JLeaf lf,JPage parent){
        this.parent=parent;
        this.leaf=lf;
        this.setTitle("オブジェクトオプション");
        text.setText(leaf.getName());
        locked.setSelected(leaf.isLocked());
        visible.setSelected(leaf.isVisible());
        this.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        text = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        locked = new javax.swing.JCheckBox();
        visible = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        jLabel1.setText("\u540d\u79f0:");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.setDefaultCapable(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        locked.setText("\u30ed\u30c3\u30af");
        locked.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        locked.setMargin(new java.awt.Insets(0, 0, 0, 0));

        visible.setText("\u53ef\u8996");
        visible.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        visible.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visible)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locked))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locked)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visible)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
// TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
// TODO add your handling code here:
        if (text.getText().equals(leaf.getName()) && locked.isSelected()==leaf.isLocked()){
            this.setVisible(false);
            return;
        }
        if (!text.getText().equals(leaf.getName())){
            SortedMap map=leaf.getPage().getNameTable();
            if (map.containsKey(text.getText())){
                JOptionPane.showMessageDialog(this,"入力されたオブジェクトの名称は、他で使用されています.");
                text.setText(leaf.getName());
                text.requestFocus();
                return;
            }
        }
        ObjectOptionEdit anEdit=new ObjectOptionEdit(leaf.getDocument().getViewer(),leaf,visible.isSelected(),locked.isSelected(),text.getText());
        leaf.getDocument().fireUndoEvent(anEdit);
        leaf.getDocument().getViewer().repaint();
        this.getParent().repaint();
        this.setVisible(false);
        
    }//GEN-LAST:event_okActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox locked;
    private javax.swing.JButton ok;
    private javax.swing.JTextField text;
    private javax.swing.JCheckBox visible;
    // End of variables declaration//GEN-END:variables
    
}
