/*
 * FontSizeOption.java
 *
 * Created on 2008/06/03, 20:51
 */

package jdraw.typemenus;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Insets;
import java.awt.Rectangle;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author  takashi
 */
public class FontSizeOption extends javax.swing.JDialog implements ChangeListener{
    private int value=0;
    private static boolean okButton=false;
    /** Creates new form FontSizeOption */
    public FontSizeOption(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fontSize.setMaxValue(new Integer(2000));
        fontSize.setMinValue(new Integer(0));
        fontSize.setIntValue(12);
        fontSlider.setValue(12);
        fontSize.addChangeListener(this);
        fontSlider.addChangeListener(this);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
    }
    private static  Frame getFrame(Component c){
        if (c instanceof Frame) return (Frame)c;
        if (c==null) return null;
        return getFrame(c.getParent());
    }
    public static int showAsDialog(Component c,int initialValue){
        Frame f=getFrame(c);
        FontSizeOption option=new FontSizeOption(f,true);
        if (f==null){
            Dimension d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            Insets is=java.awt.Toolkit.getDefaultToolkit().getScreenInsets(option.getGraphicsConfiguration());
            int x=(d.width-is.left-is.right-option.getWidth())/2;
            int y=(d.height-is.top-is.bottom-option.getHeight())/2;
            option.setLocation(x,y);
        }else{
            Rectangle r=f.getBounds();
            Insets  is=f.getInsets();
            int x=(r.width-is.left-is.right-option.getWidth())/2+r.x;
            int y=(r.height-is.top-is.bottom-option.getHeight())/2+r.y;
            option.setLocation(x,y);
        }
        okButton=false;
        option.setValue(initialValue);
        option.setVisible(true);
        return option.getValue();
    }
    public void setValue(int v){
        value=v;
        fontSize.setIntValue(v);
        fontSlider.setValue(v);
    }
    public static boolean getResult(){
        return okButton;
    }
    public int getValue(){
        return value;
    }
    public void stateChanged(ChangeEvent e) {
        if (e.getSource()==fontSize)
            fontSlider.setValue(fontSize.getIntValue());
        else
            fontSize.setIntValue(fontSlider.getValue());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fontSize = new jtools.jcontrol.JDIntegerTextField();
        jLabel1 = new javax.swing.JLabel();
        fontSlider = new jui.color.JDSlider();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("フォントサイズ");

        fontSlider.setMaxValue(100);

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("キャンセル");
        cancel.setDefaultCapable(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fontSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fontSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing
    
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
// TODO add your handling code here:
        value=fontSize.getIntValue();
        okButton=true;
        this.dispose();
    }//GEN-LAST:event_okActionPerformed
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private jtools.jcontrol.JDIntegerTextField fontSize;
    private jui.color.JDSlider fontSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
    
}
